apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    run: result
  name: result
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: result
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: result
    spec:
      containers:
      - image: gcr.io/example-project/result:1.2
        imagePullPolicy: IfNotPresent
        name: result
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - name: config-volume
          mountPath: /app/views/config
      volumes:
      - name: config-volume
        configMap:
          name: configmap-result       
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
